// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2z8piOInQm8bFa5ybn-IXgX2S7P34MwU',
    appId: '1:769614705006:web:3fdcda402da4e9c02a117f',
    messagingSenderId: '769614705006',
    projectId: 'instagrambloc-73210',
    authDomain: 'instagrambloc-73210.firebaseapp.com',
    storageBucket: 'instagrambloc-73210.appspot.com',
    measurementId: 'G-9G3ZJBLRXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALESCk-muFh8tjn7PF8GKiopcxCjyxSrM',
    appId: '1:769614705006:android:2142d465f4dfd4e92a117f',
    messagingSenderId: '769614705006',
    projectId: 'instagrambloc-73210',
    storageBucket: 'instagrambloc-73210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHz0q6QhSWVkd36w0w5_mLH5WTLvFkabo',
    appId: '1:769614705006:ios:a778b16d1c7bfe9a2a117f',
    messagingSenderId: '769614705006',
    projectId: 'instagrambloc-73210',
    storageBucket: 'instagrambloc-73210.appspot.com',
    iosClientId: '769614705006-klr51oi5erlirtgbkpbglr0kj0dg7na0.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramBloc',
  );
}
